### ISSUE TITLE
Additional page fields for backend layouts included via pagets are not visable

### ISSUE THREAD

**Issue by janamedick** [Gernott/mask#283]
There seems to be a bug, where additional fields for backendlayouts, which are included via pagets, do not show up in the "edit page" form.  
Maybe there is another bug with loosing the backend sorting because of the "parent"-field. But i could not figure it out yet.

**Comment by butu** [comment]
The Bug with the missing fields should be fixed in master and will be released with the next version

**Comment by janamedick** [comment]
you are right! I thought I had the latest version installed. Issue is fixed. Thanks!

**Comment by rupasix** [comment]
Something must have gone wrong later because I still can't see the fields in the pagets backend_layout page setup.
