### ISSUE TITLE
[BUG] nullable type crash

### ISSUE THREAD

**Issue by weisgerberm** [Gernott/mask#676]
Hi,

Since TYPO3 13.4.9 we get an exception if we want to edit any content element in the backend.
The mask extension is installed in version 9.0.7.
PHP 8.3.8

(1/1) TypeError
TYPO3\CMS\Core\Domain\DateTimeFactory::fromDatabase(): Argument #2 ($isNullable) must be of type bool, int given, called in /var/www/html/typo3_src/typo3/sysext/core/Classes/Domain/DateTimeFactory.php on line 45

We fixed this by changing a line in:
**EXT:mask/Classes/Definition/TcaFieldDefinition.php:673**
to: **$definition['config']['nullable'] = true;**

and additionally in our **mask.json** config all occurances of 
**"nullable": 0,** to "**nullable": false,**

Thank you

**Comment by nhovratov** [comment]
Fixed in Core.

**Comment by BernhardLux** [comment]
Sorry,
the bug seems to persist. After upgrading from 13.4.7 to 13.4.9 Mask content elements still can't be edited. What I also recognized, that in database analyzer following suggestion comes:
ALTER TABLE `sys_refindex` CHANGE `hash` `hash` VARCHAR(32) CHARACTER SET ascii DEFAULT '' NOT NULL COLLATE `ascii_bin`
Current value: `hash` VARCHAR(32) DEFAULT '' NOT NULL
But also after doing this the issue with mask elements remains.

**Comment by nhovratov** [comment]
The fix will be in TYPO3 13.4.10
